# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47dcf8c5f3c4a4895cad1ef670d020712551e6f412ef285c7fd96d2999d6c6b4312b1f452ea154669c164ab891deec94a1ba556382df0687fc830bc820782b2d

test:
  secret_key_base: cd0be291101ddd0e1de55020054a1cbb8cf9f2f20dbefb4ce566dee3c8a306785e315b0b18d5a158e3dbafba395fecbb046ced8bbc8200c105cf753f98cf05f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
